---
title: "Publications"
description-meta: "Information, pdfs, and social metrics of papers"
#page-layout: full
#back-to-top-navigation: true
title-block-banner: false
css: custom.css
---


<!--Include academic icons or buttons-->
{{< include /files/includes/_academic.qmd >}}


## Publications and Conference Papers

**Khanal, K.**, Michelén Ströfer, C. A., Ancellin, M., & Haji, M. (2024). Fully Differentiable Boundary Element Solver for Hydrodynamic Sensitivity Analysis of Wave-Structure Interactions. *Applied Ocean Research*, Submitted.

**Khanal, K.**, & Haji, M. N. (2024). Multi-Objective Multidisciplinary Optimization of Wave Energy Converter Array Layout and Controls. [https://dx.doi.org/10.2139/ssrn.4891821](https://dx.doi.org/10.2139/ssrn.4891821)

McCabe, R., **Khanal, K.**, & Haji, M. (2024). Open-source toolbox for semi-analytical hydrodynamic coefficients via the matched eigenfunction expansion method. *UMERC Conference*, August 7, Duluth, Minnesota.

**Khanal, K.**, & Haji, M. N. (2022, October 25). Multidisciplinary Design Optimization for Novel Offshore Systems. *Presentation at the openMDAO Workshop*, NASA Glenn Research Center, Cleveland, Ohio.

**Khanal, K.**, McCabe, R., & Haji, M. N. (2023). Gradient-Based Design Optimization of Concentric Cylindrical Offshore Structures. *Proceedings of the SIAM Conference on Optimization (OP23)*, May 31, Seattle, Washington.

**Khanal, K.**, Vitale, O., DeGoede, N., & Haji, M. (2023, October 4-6). Multi-objective Multidisciplinary Optimization of Wave Energy Converter Array Configurations and Controls. *University Marine Energy Research Community 2023 Conference*, Durham, NH, USA.

<center><hr style="width:50%"></center>

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}