---
title: "Software & Projects"
subtitle: "A collection of tools, libraries, and projects I've developed."
page-layout: full
---

This page highlights the software projects and computational tools I have developed and contributed to. These projects reflect my interest in creating robust, scalable, and efficient solutions for complex engineering and scientific problems.

More details and project listings will be added here soon.

***

### Featured Projects

:::{.grid}

::: {.g-col-12 .g-col-md-6}
#### [MarineHydro.jl](https://github.com/symbiotic-engineering/MarineHydro.jl)
A Boundary Element Method (BEM) solver written in Julia, designed for hydrodynamic analysis within a fully differentiable programming paradigm. It leverages automatic differentiation for efficient gradient computation.
:::

::: {.g-col-12 .g-col-md-6}
#### Differentiable wave2wire Framework for WEC Farms
An framework for the Multidisciplinary Design Optimization of Wave Energy Converters (WECs) and WEC Farms. This project integrates hydrodynamic of large number of WECs, and control system models to optimize the performance of the WEC farm using gradient-based optimization.
:::

::: {.g-col-12 .g-col-md-6}
#### openFlash
An open-source framework built to simulate the hydrodynamics of wave energy converters using matched eigenfunction expansion methods.
:::


:::
</rewritten_file> 